version: '3.8'

services:
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
        MYSQL_ROOT_PASSWORD: ""
        MYSQL_DATABASE: laravel
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '4309:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/laravel
    working_dir: /var/www/laravel
    depends_on:
      - database
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8081:80'
    volumes:
        - .:/var/www/laravel
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
